///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String acheivementSelectedTabIcon = 'assets/images/acheivement_selected_tab_icon.png';
  static const String appIcon = 'assets/images/app_icon.png';
  static const String darkPageBg = 'assets/images/dark_page_bg.png';
  static const String donationImageBg = 'assets/images/donation_image_bg.png';
  static const String femaleGreenAvatarIcon = 'assets/images/female_green_avatar_icon.png';
  static const String maleGreenAvatarIcon = 'assets/images/male_green_avatar_icon.png';
  static const String neuss = 'assets/images/neuss.png';
  static const String noConnection = 'assets/images/no_connection.png';
  static const String otp = 'assets/images/otp.flr';
  static const String pageBg = 'assets/images/page_bg.png';
  static const String serverErrorIcon = 'assets/images/server_error_icon.png';
  static const String whatsappIcon = 'assets/images/whatsapp_icon.svg';

}
